matrix:
- name: Markdown
  aspell:
    lang: fr
    d: fr_FR
  dictionary:
    encoding: utf-8
    wordlists:
    - .wordlist.txt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '_posts/*.md'
  default_encoding: utf-8
